// AUTO-GENERATED by scripts/import-listings.mjs — do not hand-edit.
// Edit incoming/listings.csv and run `npm run import-listings` instead.
import type { Product } from "./data";

export const GENERATED_PRODUCTS: Product[] = [];
